variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
    paths:
        - "$CI_PROJECT_DIR/pip-cache"
    key: "$CI_PROJECT_ID"

stages:
    - test
    - deploy

before_script:
    - pip install --user tox
    - export PATH="$HOME/.local/bin:$PATH"

unit tests:
    stage: test
    script: tox -e py27
    tags: [memopol]

qa checks:
    stage: test
    script: tox -e qa
    tags: [memopol]

docs build:
    stage: test
    script: git diff --raw HEAD^1 | grep docs || tox -e docs
    tags: [memopol]

docs deploy:
    stage: deploy
    script:
        - source /srv/memopol/memopol_env/bin/activate
        - cd /srv/memopol/memopol_env/src/memopol/docs
        - make html
    tags: [memopol]
    environment: production
    only:
        - master

django deploy:
    stage: deploy
    script:
        - source /srv/memopol/memopol_env/bin/activate
        - cd /srv/memopol/memopol_env/src/memopol
        - git fetch origin
        - git reset --hard origin/master
        - find . -name '*.pyc' -delete
        - pip install -Ue .
        - src/memopol/bin/install_client_deps.sh
        - memopol migrate --noinput
        - memopol collectstatic --noinput
        - touch /srv/memopol/ready
    tags: [memopol]
    environment: production
    only:
        - master
