sudo: false
env:
  global:
  - DJANGO_DEBUG=True
  - DJANGO_SETTINGS_MODULE=memopol.settings
  matrix:
  - TOXENV=qa
  - TOXENV=docs
  - TOXENV=py27
language: python
python:
- '3.4'
services:
- postgresql
install:
- travis_retry pip install -U pip
- travis_retry pip install tox
- travis_retry pip freeze
before_script:
- psql -c "CREATE USER memopol WITH CREATEDB PASSWORD 'memopol';" -U postgres
- psql -c "CREATE DATABASE memopol WITH OWNER memopol;" -U postgres
script:
- travis_retry tox
after_success:
- codecov
deploy:
- provider: openshift
  edge: true
  user: memopol@laquadrature.net
  password:
    secure: atDq1NEkHXOsV2gZKeXAIn+PvbL3jduz3WK1qIs7BSHyNbrZMT1OUmvoXXrM8+i5eqW3TNsvp23w0RuD06wxSjHkPl+ZCEXP1Ao98p85UZNCgixxiwZHEhL6Amz5vqueGhv+47VOIKNgNFb9NAtRrWyIdA9xDUiK2oWkMSDmHas=
  app: master
  domain: memopol
  deployment_branch: master
  on:
    repo: memopol/memopol master
